### ISSUE TITLE
Header Text

### ISSUE THREAD

**Issue by cw79** [berlin-bakers-against-racism/berlin-bakers-against-racism.github.io#6]
Hi Berliners!

Together with 20+ bakers in the city, Berlin Bakers Against Racism is hosting a bake sale to raise funds to fight against systemic racism. 100% proceeds donated to Equal Justice Initiative and KOP-Berlin.

Bake sale is now open and taking orders until Wednesday. Contribute to the fight for justice AND satisfy your sweet tooth! Limited goods available- So hurry before they’re gone! 

Bakers Against Racism is an initiative started in the US by  @smallorchids @badwolf_88 & @robrubba to fight for justice. Their initiative is now in 15 countries world wide including here in Berlin!
 
https://www.instagram.com/berlinbakersagainstracism/
https://www.instagram.com/bakersagainstracism/

#bakersagainstracism #berlinbakersagainstracism #blacklivesmatter #blacklivesmatterberlin #blmberlin

**Comment by berlin-bakers-against-racism** [comment]
Live now.
![image](https://user-images.githubusercontent.com/66932821/84768763-0f6e4080-afd5-11ea-9f89-0acb23d2c466.png)
